### ISSUE TITLE
Adding Python types

### ISSUE THREAD

**Issue by sbdchd** [indygreg/python-zstandard#120]
Was wondering your thoughts on adding types directly to this project to support `mypy` and similar tools.

Otherwise, would you be okay with me (or someone else) adding types for this package to the [python/typeshed](https://github.com/python/typeshed/)?

related: https://www.python.org/dev/peps/pep-0561/
related: https://www.python.org/dev/peps/pep-0484/

**Comment by indygreg** [comment]
I am 100% in favor of adding type annotations. And since `main` dropped support for Python 2, we can even add them inline.

However, we can't simply add type annotations to C/Rust extensions. So we may have to do something sneaky to trick mypy and other tools to recognize the annotations.

I also have a strong preference for adding type annotations to this repo, as I don't want to worry about syncing them with a 3rd party repo.

What's the state of the art for defining type annotations for code implemented by C extensions?

**Comment by sbdchd** [comment]
Great! Having the types in the repo is definitely better than having to keep them in sync with the typeshed.

As for typing native extensions, I think we'd need to define type stubs aka `.pyi` files along with the `py.typed` file mentioned in https://www.python.org/dev/peps/pep-0561/#packaging-type-information

**Comment by animalize** [comment]
> What's the state of the art for defining type annotations for code implemented by C extensions?

Type annotations can be put in `__init__.pyi` file.
And add a 0-byte file `py.typed`, it indicates that the module supports type hints, this file is for `mypy`.

Here's an example:
https://github.com/animalize/pyzstd/tree/dev/src
(And add them in `setup.py` script)

On the current trend, maybe one day zstd will be included in Python standard library, so I wrote this module.

**Comment by indygreg** [comment]
I've committed a `.pyi` file for `zstandard`. Please file new issues if you run into any problems with the type annotations. I'm in the process of adding CI coverage for the type annotations to help ensure they are accurate.
