### ISSUE TITLE
Question: Why can't the decompressor seek backwards?

### ISSUE THREAD

**Issue by NostalgiaRunner** [indygreg/python-zstandard#149]
Hello,

It's not a huge deal, but I'm wondering why the ZstdDecompressor can only seek forwards and throws and error if seeking back to 0. I'm just trying to understand the reasoning behind it. Is it an artificial limitation? Is there a better interface to use if I want to be able to seek back in a zstd compressed file? 

Thank you.

**Comment by indygreg** [comment]
Seeking forwards requires merely decompressing more data and ignoring bytes until you get to the offset you want.

Seeking backwards requires reconstructing decompressor state in order to reconstitute those bytes. This often means replaying the original compressed stream over again until you get to the desired offset. This is possible (albeit inefficient) for files. For actual streams where you've thrown the original source bytes away, it is impossible.

A compromise solution is to maintain a window buffer of the last N decompressed bytes and support seeking backwards into that buffer. This feature is possible to implement. But it adds complexity and some performance overhead (since you need to write decompressed bytes to both a Python object and the "lookback" window buffer).

For streams that are reverse seekable, we _could_ enable support so reverse seeking _just works_. But it is a performance footgun. At the point you need to replay the entire stream, the caller of the library could just as easily start a new decompression operation. I'd rather not support automatic reverse seeking and let the caller decide what the most reasonable action is in this case.

**Comment by NostalgiaRunner** [comment]
That was a fantastic explanation. Thank you for that! That makes a lot of sense and I'll keep that in mind with my project. Thank you and take care.
