### ISSUE TITLE
ZstdDecompressor stream_reader doesn't support readline()

### ISSUE THREAD

**Issue by gcp** [indygreg/python-zstandard#39]
The documentation for ZstdCompressor explicitly says that stream_reader's file-like object doesn't support readline() because it makes no sense for compressed data. For Decompressor, this remark is missing - as it should be - but the function doesn't seem to be implemented and throws NotImplementedError.

**Comment by gcp** [comment]
https://github.com/indygreg/python-zstandard/blob/b3b44ff4cfaf8e992aba12cbc412fd007066035d/c-ext/decompressionreader.c#L263

**Comment by indygreg** [comment]
I'm going to call this a duplicate of #13.

I have a patch for `readline()` that's been sitting around. I need to polish it up and land it. I'm not a fan of adding a buffering layer in order to provide `readline()`. But enough consumers want a file-like object and `readline()` is part of that interface. So it should be implemented. I'll try to deliver this in the 0.9 release.
